spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
      username: micro
      password: micro
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
